version: '3.7'

services:
  teamforward:
    build:
      context: .
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: teamforward-api 
    expose:
      - '8080'
    ports:
      - '4000:4000'
    command: npm run dev